export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA';
export const CLEAR_USERS_DATA ='CLEAR_USERS_DATA';

export const SET_IMAGE = 'SET_IMAGE';
export const DISPLAY_IMAGE = 'DISPLAY_IMAGE';
export const RESET_IMAGE = 'RESET_IMAGE';
export const FILL = 'FILL';
export const SET_NAME = 'SET_NAME';
export const SET_POSTS = 'SET_POSTS';

//sets profile picture by having redux store the pictures unique ID
export const SET_PROFILEPIC = 'SET_PROFILEPIC';
export const SET_PROFILEPICURL = 'SET_PROFILEPICURL';
export const VISIT_PROFILE = 'VISIT_PROFILE';
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';

export const ADD_TARGET = 'ADD_TARGET';
export const COLLECT_TARGET_POSTS = 'COLLECT_TARGET_POSTS';